substitutions:
  devicename: conico1
  proper_devicename: Conico1

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  arduino_version: espressif8266@2.6.2

wifi:
  ssid: !secret ssid
  password: !secret ssid_password
  use_address: "$devicename.home"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$proper_devicename Hotspot"
    password: !secret ap_password

captive_portal:
logger:
api:
ota:

# binary_sensor:
#   - platform: gpio
#     pin:
#       number: GPIO13
#       mode: INPUT_PULLUP
#     id: button
#     on_press:
#       - switch.toggle: relay

#   - platform: status
#     name: $devicename

switch:
  - platform: gpio
    name: $devicename
    pin: GPIO14   #Verified not inverted
    id: relay
    icon: "mdi:floor-lamp"
    #inverted: yes

    on_turn_on:
      - output.turn_on: led2
      - output.turn_on: led3
    on_turn_off:
      - output.turn_off: led2
      - output.turn_off: led3

#Blue
output:
  - platform: gpio
    pin: GPIO13
    id: led2
    inverted: yes

  #Test
  - platform: gpio
    pin: GPIO12
    id: led3
    inverted: yes

#Red
status_led:
  pin:
    number: GPIO4
    inverted: yes
