substitutions:
  devicename: nodemcu_9de8f9
  proper_devicename: Nodemcu_9DE8F9

esphome:
  name: $devicename
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret ssid
  password: !secret ssid_password
  use_address: "$devicename.home"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $proper_devicename Hotspot
    password: !secret ap_password

captive_portal:
logger:
api:
ota:

binary_sensor:
  - platform: status
    name: "$proper_devicename"

status_led:
  pin:
    number: GPIO16  #D0    #GPIO16
    inverted: yes

